FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod main.go .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags '-extldflags "-static"' -o go-app .

FROM gcr.io/distroless/static-debian13
WORKDIR /app
USER nonroot
COPY --from=builder /app/go-app .
EXPOSE 8080
CMD ["/app/go-app"]
